#!/usr/bin/env bash
#
# Builds exampleSite into ./public as the theme's public demo — once per color
# scheme, so visitors can see all four phosphors:
#
#   /               amber (P3), the default, full CRT effects
#   /green/         green (P1)          /blue/  blue     /white/  white
#   /plain/         same, effects off — and /<scheme>/plain/ for the others
#
# Eight builds in total: four phosphors x {full effects, effects off}.
#
# Intended as the build command for a Cloudflare Pages project pointed at this
# repository:
#
#   Build command:        bash scripts/build-demo.sh
#   Build output directory: public
#   Environment variable:   HUGO_VERSION = 0.164.0
#
# The base URL falls back to CF_PAGES_URL, which Cloudflare sets per deployment,
# so preview builds get correct absolute URLs with no extra configuration.
#
# IF YOU ATTACH A CUSTOM DOMAIN, set BASE_URL to it in the Pages project's
# production environment variables: CF_PAGES_URL is the *.pages.dev address even
# on production builds, so without BASE_URL the canonical tags, feed links and
# share images would all point at pages.dev instead of the custom domain.
# BASE_URL also lets the script run anywhere else, including locally.
#
# Runs fine on a laptop too:
#   BASE_URL=http://localhost:8080/ bash scripts/build-demo.sh && \
#     python3 -m http.server 8080 -d public

set -euo pipefail

HUGO_VERSION="${HUGO_VERSION:-0.164.0}"
SCHEMES=(green blue white)          # amber is the default and builds at the root
OUT="${OUT:-public}"

# ---------------------------------------------------------------------------
# Base URL
# ---------------------------------------------------------------------------
BASE="${BASE_URL:-${CF_PAGES_URL:-http://localhost:1313/}}"
BASE="${BASE%/}/"                   # exactly one trailing slash
echo "==> base URL: $BASE"

# ---------------------------------------------------------------------------
# Hugo. Two requirements, and a host's preinstalled binary can fail either:
#   * extended — the theme compiles SCSS with toCSS
#   * >= MIN_HUGO — layouts/_markup/ render hooks need the 0.146 template system
# A build image that ships an old extended binary would otherwise get past a
# bare "is it extended?" check and fail later with a confusing template error.
# ---------------------------------------------------------------------------
MIN_HUGO="0.146.0"                  # keep in sync with theme.toml min_version

usable_hugo() {                     # usable_hugo <path> -> 0 if extended and new enough
  local bin="$1" v
  [ -x "$bin" ] || return 1
  "$bin" version 2>/dev/null | grep -q extended || return 1
  v="$("$bin" version 2>/dev/null | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1 | tr -d v)"
  [ -n "$v" ] || return 1
  [ "$(printf '%s\n%s\n' "$MIN_HUGO" "$v" | sort -V | head -1)" = "$MIN_HUGO" ]
}

HUGO_BIN="$(command -v hugo || true)"
if usable_hugo "$HUGO_BIN"; then
  echo "==> using Hugo on PATH"
else
  if [ -n "$HUGO_BIN" ]; then
    echo "==> Hugo on PATH is unusable ($("$HUGO_BIN" version 2>&1 | head -1))"
    echo "    need extended, >= $MIN_HUGO"
  else
    echo "==> no Hugo on PATH"
  fi
  echo "==> downloading Hugo v${HUGO_VERSION} extended"
  tmp="$(mktemp -d)"
  url="https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
  curl -fsSL "$url" -o "$tmp/hugo.tar.gz"
  tar -xzf "$tmp/hugo.tar.gz" -C "$tmp" hugo
  HUGO_BIN="$tmp/hugo"
  usable_hugo "$HUGO_BIN" || { echo "ERROR: downloaded Hugo is still unusable" >&2; exit 1; }
fi
"$HUGO_BIN" version

# ---------------------------------------------------------------------------
# Scheme switcher, injected through the theme's own documented custom_footer.html
# hook. Generated here so exampleSite stays a clean starter config in the repo.
# ---------------------------------------------------------------------------
mkdir -p exampleSite/layouts/partials
cat > exampleSite/layouts/partials/custom_footer.html <<'HTML'
{{- /* Generated by scripts/build-demo.sh — not part of the theme.
       Rendered at the end of <body> (the only body-level hook the theme
       exposes) but pinned to the top of the viewport, so it reads as a demo
       banner rather than a page element.

       Two axes: phosphor and effects. Each link preserves the other axis, so
       switching palette keeps you in the same effects mode and vice versa. */ -}}
{{- $scheme := site.Params.scanlines.colorScheme | default "amber" -}}
{{- $plain  := eq site.Params.scanlines.effects.enabled false -}}
{{- $suffix := cond $plain "plain/" "" -}}
{{- $base   := cond (eq $scheme "amber") "/" (printf "/%s/" $scheme) -}}
{{- /* This page's path within its own variant, so switching keeps your place
       instead of bouncing you to the variant's homepage. Every variant builds
       the same content, so the path always exists on the other side. */ -}}
{{- $here := strings.TrimPrefix site.Home.RelPermalink .RelPermalink -}}
<style>
:root { --demo-bar-h: 2.4rem; }
body { padding-top: var(--demo-bar-h); }
.demo-bar{
  position:fixed; top:0; left:0; right:0; z-index:200;
  /* safe centring: a plain "center" makes the overflowing left edge
     unreachable once the bar is wider than the viewport */
  display:flex; align-items:center; justify-content:safe center; gap:.15em;
  height:var(--demo-bar-h); padding:0 var(--spacing-sm);
  background:var(--color-bg-secondary);
  border-bottom:1px solid var(--color-border);
  font-family:var(--font-terminal); font-size:.7rem;
  letter-spacing:.1em; text-transform:uppercase;
  color:var(--color-fg-dim); overflow-x:auto; white-space:nowrap;
}
.demo-bar .demo-label{ margin:0 .4em 0 0; }
.demo-bar .demo-sep{ margin:0 .6em; opacity:.5; }
.demo-bar a{ color:var(--color-fg); text-decoration:none; padding:0 .3em; }
.demo-bar a:hover,.demo-bar a:focus{ color:var(--color-fg-bright); }
.demo-bar a::before{ content:"[ "; color:var(--color-fg-dim); }
.demo-bar a::after{ content:" ]"; color:var(--color-fg-dim); }
.demo-bar a[aria-current="page"]{ color:var(--color-fg-bright); }
.demo-bar a[aria-current="page"]::before{ content:"[*"; }
.demo-bar a[aria-current="page"]::after{ content:"*]"; }
@media print { .demo-bar{ display:none; } body{ padding-top:0; } }
</style>
<nav class="demo-bar" aria-label="Demo options">
  <span class="demo-label">Phosphor</span>
  {{- range slice "amber" "green" "blue" "white" }}
  {{- $href := printf "%s%s%s" (cond (eq . "amber") "/" (printf "/%s/" .)) $suffix $here }}
  <a href="{{ $href }}"{{ if eq . $scheme }} aria-current="page"{{ end }}>{{ . }}</a>
  {{- end }}
  <span class="demo-sep" aria-hidden="true">|</span>
  <span class="demo-label">Effects</span>
  <a href="{{ printf "%s%s" $base $here }}"{{ if not $plain }} aria-current="page"{{ end }}>Full</a>
  <a href="{{ printf "%splain/%s" $base $here }}"{{ if $plain }} aria-current="page"{{ end }}>Off</a>
</nav>
HTML
trap 'rm -rf exampleSite/layouts "${THEMES:-}"' EXIT

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
build() {                            # build <destination> <baseURL> [config...]
  local dest="$1" base="$2"; shift 2
  local args=(--source exampleSite --themesDir "$THEMES"
              --baseURL "$base" --destination "$dest"
              --gc --minify --logLevel info)
  [ "$#" -gt 0 ] && args+=(--config "$1")
  "$HUGO_BIN" "${args[@]}" 2>&1 | tee /tmp/demo-build.log
  if grep -qiE "WARN|deprecated" /tmp/demo-build.log; then
    echo "ERROR: Hugo emitted warnings (see above)" >&2
    exit 1
  fi
}

ROOT="$PWD"
rm -rf "${ROOT:?}/$OUT"

# ---------------------------------------------------------------------------
# Theme lookup. exampleSite sets theme = "scanlines", so Hugo needs a directory
# of that name inside --themesDir. Passing ../.. only works when the checkout is
# itself named "scanlines" (true in GitHub Actions, false on Cloudflare Pages,
# which clones to /opt/buildhome/repo). Build an explicit themes dir instead, so
# the name of the checkout directory doesn't matter.
# ---------------------------------------------------------------------------
THEMES="$(mktemp -d)"
ln -sfn "$ROOT" "$THEMES/scanlines"
echo "==> theme linked at $THEMES/scanlines -> $ROOT"

# Every scheme is built twice: full effects, then effects off at /<scheme>/plain/.
# Parent before child, since the plain build nests inside the scheme's directory.
for scheme in amber "${SCHEMES[@]}"; do
  if [ "$scheme" = amber ]; then dir=""; else dir="$scheme/"; fi

  printf '[params.scanlines]\ncolorScheme = "%s"\n' "$scheme" > "/tmp/demo-$scheme.toml"
  echo "==> building $scheme at ${BASE}${dir}"
  build "$ROOT/$OUT/${dir%/}" "${BASE}${dir}" "hugo.toml,/tmp/demo-$scheme.toml"

  printf '[params.scanlines]\ncolorScheme = "%s"\n[params.scanlines.effects]\nenabled = false\n' \
    "$scheme" > "/tmp/demo-$scheme-plain.toml"
  echo "==> building $scheme (effects off) at ${BASE}${dir}plain/"
  build "$ROOT/$OUT/${dir}plain" "${BASE}${dir}plain/" "hugo.toml,/tmp/demo-$scheme-plain.toml"
done

echo "==> built $(find "$ROOT/$OUT" -name '*.html' | wc -l) pages into $OUT/"
